### PR TITLE
Fix collapsion of a block in a case when a line contains "do"

### LINKED ISSUE #15: RSpec let when do in variable name
``` ruby
let(:domain) { 'test' }
```

converts to:

``` ruby
let(:do
main) do 'test'
end
```

should be:

``` ruby
let(:domain) do
  'test'
end
```

### PR DESCRIPTION
**Pull request by KirillKayumov**
Fixes #15

### CODE REVIEW

**Comment by KirillKayumov** [comment]
@dsandstrom could you please review? Thanks!

**Comment by dsandstrom** [comment]
@KirillKayumov Thank you for the pr, will review.

**Comment by dsandstrom** [comment]
Thanks again for the PR and excellent test.  I feel like the regex is overly complicated.  Would something like this work instead?

```
@buffer.scanInRange /\sdo/, newStartRange, (obj) ->
  obj.replace " do\n"
  joined = true
```

**Comment by KirillKayumov** [comment]
@dsandstrom, yes, the regex you provided is suitable for the most of cases, but there is still one edge case which the regex doesn't cover:
```ruby
describe("let\'s do it"){ it { is_expected.to eq(42) } }
```

Here we have ` do` inside the passed argument and a block which has no indentation. If we used `/\sdo/` regex, we would have the following changes:

1.
```ruby
describe("let\'s do it"){ it { is_expected.to eq(42) } }
```
2.
```ruby
describe("let\'s do it")do it { is_expected.to eq(42) } end
```
3.
```ruby
describe("let\'s do 
it")do it { is_expected.to eq(42) } 
end
```

I've slightly updated my regex, here's the explanation:
`/(?!do\w.*do(?!\w))\s?do/`

1. `\s?do` is finds "do" or " do"
2. `(?!do\w.*do(?!\w))`
2.a. `do(?!\w)` – accepts only those `do` whose are NOT appended by an alphanumeric symbol. Examples:
- "**do** " – accepted
- "**do**{" – accepted
- "**do**main" – NOT accepted
2.b. `do\w.*do(?!\w)` – accepts only those `do` whose ARE followed by `do` from 2.a. Examples:
- "...**do**main) do { ... }" – accepted
3. `/(?!do\w.*do(?!\w))\s?do/` – accepts only those `do` whose accepted in 1 AND are NOT accepted in 2.b.

**Comment by KirillKayumov** [comment]
@dsandstrom hey! Can we merge the PR?

**Comment by dsandstrom** [comment]
Merged, but I want to try it out before publishing a new version.

**Pull request merged**
